"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("./assets/main.css");
var vue_1 = require("vue");
var App_vue_1 = require("./App.vue");
var index_ts_1 = require("./router/index.ts");
var vue_toastification_1 = require("vue-toastification");
require("vue-toastification/dist/index.css");
var app = (0, vue_1.createApp)(App_vue_1.default);
app.use(index_ts_1.default);
app.use(vue_toastification_1.default);
app.mount('#app');
